server:
  port: 8084
  servlet:
    context-path: /api/v1
spring:
  application:
    name: helpmeiud
  #conexión a base de datos
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  # generar tablas
  jpa:
    hibernate:
      ddl-auto: update